nameOverride: ""
fullnameOverride: ""
plugin:
  enabled: true
  versionOverride: ""
  endpoint: >-
    https://raw.githubusercontent.com/rancher/virtual-clusters-ui/gh-pages/extensions/virtual-clusters/1.1.0
  compressedEndpoint: >-
    https://raw.githubusercontent.com/rancher/virtual-clusters-ui/gh-pages/extensions/virtual-clusters/1.1.0.tgz
  noCache: false
  noAuth: false
  metadata:
    catalog.cattle.io/display-name: Virtual Clusters
    catalog.cattle.io/ui-extensions-version: ">= 3.0.0 < 4.0.0"
    catalog.cattle.io/rancher-version: ">=2.13.0"
    catalog.cattle.io/prime-only: "true"
