#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
BASE_DIR="$( cd $SCRIPT_DIR && cd .. & pwd)"

CYAN="\033[96m"
YELLOW="\033[93m"
RED="\033[31m"
GREEN="\033[32m"
RESET="\033[0m"
BOLD="\033[1m"

ORG=rancher
BRANCH=main

OVERALL_ERROR="false"

echo -e "${CYAN}${BOLD}Sync Extensions checks${RESET}"

EXTS=$(jq -r ".extensions | keys[]" manifest.json)

TMP=${BASE_DIR}/tmp
rm -rf ${TMP}
mkdir -p ${TMP}

REPOSITORY=${ORG}/ui-plugin-charts

echo "GitHub Repository: ${REPOSITORY}"
echo "GitHub Branch:     ${BRANCH}"

# syncing new charts into this repo
# let's go over all the extensions in the manifest to check what's synced and what's not...
for NAME in ${EXTS}
do
  echo -e "${CYAN} + Syncing: ${BOLD}${NAME}${RESET}"

  # Make diretories for assets, charts, and extensions
  mkdir -p ./assets/${NAME}
  mkdir -p ./charts/${NAME}
  mkdir -p ./extensions/${NAME}

  # Get repository name, branch, and versions
  REPO=$(jq -r ".extensions.\"${NAME}\".repo" manifest.json)
  EXT_BRANCH=$(jq -r ".extensions.\"${NAME}\".branch" manifest.json)
  VERSIONS=$(jq -r ".extensions.\"${NAME}\".versions[]" manifest.json)
  VFORMAT=$(echo $VERSIONS | tr '\n' ' ')

  echo -e "     Repository: ${REPO}"
  echo -e "     Branch: ${EXT_BRANCH}"
  echo -e "     Versions  : ${VFORMAT}"
  echo ""

  for VERSION in ${VERSIONS}
  do
    echo -e "${CYAN}     Syncing: ${BOLD}${NAME}@${VERSION}${RESET}"

    if [ -d "./charts/${NAME}/${VERSION}" ]; then
      echo "      Version already synced"
    else
      WITH_ERROR="false"

      # clone extension repository
      echo -e "  .. Cloning repository ${REPO} on branch ${EXT_BRANCH}"
      rm -rf ./tmp/${NAME}
      pushd tmp > /dev/null
      git clone -b ${EXT_BRANCH} --single-branch https://github.com/${REPO}.git ${NAME}
      cd ${NAME}
      pwd
      popd > /dev/null

      echo -e "${BOLD}${YELLOW}  .. Starting checks for extension ${NAME} version ${VERSION}${RESET}"

      # check if description exists and is non-empty in package.json
      PKG_JSON_DESCRIPTION=$(jq -r ".description" ./tmp/${NAME}/extensions/${NAME}/${VERSION}/plugin/package.json)
      PKG_JSON_VERSION=$(jq -r ".version" ./tmp/${NAME}/extensions/${NAME}/${VERSION}/plugin/package.json)

      if [[ ! -n "$PKG_JSON_DESCRIPTION" ]] || [[ "$PKG_JSON_DESCRIPTION" == null ]]; then
        echo "❌ Missing description in package.json for extension ${NAME} version ${VERSION}! Description is a mandatory field!"
        WITH_ERROR="true"
        OVERALL_ERROR="true"
      fi

      # check if description exists and is non-empty in Chart.yaml
      CHART_YAML_DESCRIPTION=$(yq -r ".description" ./tmp/${NAME}/charts/${NAME}/${VERSION}/Chart.yaml)

      if [[ ! -n "$CHART_YAML_DESCRIPTION" ]] || [[ "$CHART_YAML_DESCRIPTION" == null ]]; then
        echo "❌ Missing description in Chart.yaml for extension ${NAME} version ${VERSION}! Description is a mandatory field!"
        WITH_ERROR="true"
        OVERALL_ERROR="true"
      fi

      # check if version exists and is non-empty in package.json
      if [[ ! -n "$PKG_JSON_VERSION" ]] || [[ "$PKG_JSON_VERSION" == null ]]; then
        echo "❌ Missing version in package.json for extension ${NAME} version ${VERSION}! Version is a mandatory field!"
        WITH_ERROR="true"
        OVERALL_ERROR="true"
      fi

      # check if README exists and it's content is not empty
      README_FILE=./tmp/${NAME}/charts/${NAME}/${VERSION}/README.md

      # -f "$README_FILE": The file exists AND is a regular file.
      # $(grep -q '[^[:space:]]' "$README_FILE"): Grep finds a non-whitespace character (returns exit 0)
      if [[ ! -f "$README_FILE" ]] || ! grep -q '[^[:space:]]' "$README_FILE"; then
        echo "❌ Error: README file doesn't exist or is empty!"
        WITH_ERROR="true"
        OVERALL_ERROR="true"
      fi

      # Check the chart file for an icon
      CHART_FILE=./tmp/${NAME}/charts/${NAME}/${VERSION}/Chart.yaml

      ICON=$(yq eval '.icon' ${CHART_FILE})

      if [ -n "${ICON}" ]; then
        # Downloading icon
        ICON_FILE=$(basename $ICON)
        echo "     + Fetching icon: ${ICON}"
        ICON_REL=icons/${NAME}/${VERSION}-${ICON_FILE}
        rm -f ${BASE_DIR}/${ICON_REL}
        
        # Download the icon using curl
        set +e
        curl --location --output "${BASE_DIR}/${ICON_REL}" "$ICON"
        ERR=$?
        set -e # <--- Re-enables the 'exit immediately on error' setting

        # Icon downloaded okay
        if ! [ ${ERR} -eq 0 ]; then
          echo "❌ Warning: Could not download icon - check URL for icon in Chart.yaml"
          WITH_ERROR="true"
          OVERALL_ERROR="true"
        else
          echo "✅ Icon check succeeded"
        fi
      else
        echo "❌ Warning: Icon not found in Chart.yaml! Icon presence is mandatory!"
        WITH_ERROR="true"
        OVERALL_ERROR="true"
      fi

      if [[ "$WITH_ERROR" == "true" ]]; then
        echo -e "${RED}  .. Some checks failed for extension ${NAME} version ${VERSION}${RESET}"
      else
        echo -e "${GREEN}  .. ✅ ALL CHECKS SUCCEEDED for extension ${NAME} version ${VERSION}${RESET}"
      fi
    fi
  done
done

if [[ "$OVERALL_ERROR" == "true" ]]; then
  echo -e "${BOLD}${RED}  .. Some checks failed for the extensions this PR brings in. Check this script logs for more information${RESET}"
  exit 1
else
  exit 0
fi

# Clean up
rm -rf ${TMP}