#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
BASE_DIR="$( cd $SCRIPT_DIR && cd .. & pwd)"

CYAN="\033[96m"
YELLOW="\033[93m"
RESET="\033[0m"
BOLD="\033[1m"

ORG=rancher
BRANCH=main

echo -e "${CYAN}${BOLD}Sync Extensions checks${RESET}"

EXTS=$(jq -r ".extensions | keys[]" manifest.json)

TMP=${BASE_DIR}/tmp
rm -rf ${TMP}
mkdir -p ${TMP}

REPOSITORY=${ORG}/ui-plugin-charts

echo "GitHub Repository: ${REPOSITORY}"
echo "GitHub Branch:     ${BRANCH}"

# syncing new charts into this repo
# let's go over all the extensions in the manifest to check what's synced and what's not...
for NAME in ${EXTS}
do
  echo -e "${CYAN} + Syncing: ${BOLD}${NAME}${RESET}"

  # Make diretories for assets, charts, and extensions
  mkdir -p ./assets/${NAME}
  mkdir -p ./charts/${NAME}
  mkdir -p ./extensions/${NAME}

  # Get repository name, branch, and versions
  REPO=$(jq -r ".extensions.\"${NAME}\".repo" manifest.json)
  EXT_BRANCH=$(jq -r ".extensions.\"${NAME}\".branch" manifest.json)
  VERSIONS=$(jq -r ".extensions.\"${NAME}\".versions[]" manifest.json)
  VFORMAT=$(echo $VERSIONS | tr '\n' ' ')

  echo -e "     Repository: ${REPO}"
  echo -e "     Branch: ${EXT_BRANCH}"
  echo -e "     Versions  : ${VFORMAT}"
  echo ""

  for VERSION in ${VERSIONS}
  do
    echo -e "${CYAN}     Syncing: ${BOLD}${NAME}@${VERSION}${RESET}"

    if [ -d "./charts/${NAME}/${VERSION}" ]; then
      echo "      Version already synced"
    else
      # clone extension repository
      echo -e "  .. Cloning repository ${REPO} on branch ${EXT_BRANCH}"
      rm -rf ./tmp/${NAME}
      pushd tmp > /dev/null
      git clone -b ${EXT_BRANCH} --single-branch https://github.com/${REPO}.git ${NAME}
      cd ${NAME}
      pwd
      popd > /dev/null

      PKG_JSON_DESCRIPTION=$(jq -r ".description" ./tmp/${NAME}/extensions/${NAME}/${VERSION}/plugin/package.json)
      PKG_JSON_VERSION=$(jq -r ".version" ./tmp/${NAME}/extensions/${NAME}/${VERSION}/plugin/package.json)

      # check if description exists and is non-empty in package.json
      if [[ ! -n "$PKG_JSON_DESCRIPTION" ]] || [[ "$PKG_JSON_DESCRIPTION" == null ]]; then
        echo "Missing description is package.json! Description is a mandatory field!"
        exit 1
      fi

      # check if version exists and is non-empty in package.json
      if [[ ! -n "$PKG_JSON_VERSION" ]] || [[ "$PKG_JSON_VERSION" == null ]]; then
        echo "Missing version is package.json! Version is a mandatory field!"
        exit 1
      fi

      README_FILE=./tmp/${NAME}/charts/${NAME}/${VERSION}/README.md

      # check if README exists and it's content contains something...
      # -f "$README_FILE": The file exists AND is a regular file.
      # $(grep -q '[^[:space:]]' "$README_FILE"): Grep finds a non-whitespace character (returns exit 0)
      if [[ ! -f "$README_FILE" ]] || ! grep -q '[^[:space:]]' "$README_FILE"; then
        echo "❌ Error: README file doesn't exist or is empty!"
        exit 1
      fi

      echo "✅ README, description and version checks succeeded"

      # Check the chart file for an icon
      CHART_FILE=./tmp/${NAME}/charts/${NAME}/${VERSION}/Chart.yaml

      ICON=$(yq eval '.icon' ${CHART_FILE})

      if [ -n "${ICON}" ]; then
        # Downloading icon
        ICON_FILE=$(basename $ICON)
        echo "     + Fetching icon: ${ICON}"
        ICON_REL=icons/${NAME}/${VERSION}-${ICON_FILE}
        rm -f ${BASE_DIR}/${ICON_REL}
        
        # Download the icon using curl (available everywhere) - ignore errors temporarily
        set +e
        curl --silent --location --output "${BASE_DIR}/${ICON_REL}" "$ICON"
        echo "${curl --silent --location --output "${BASE_DIR}/${ICON_REL}" "$ICON"}"
        ERR=$?
        set -e # <--- Re-enables the 'exit immediately on error' setting

        # Icon downloaded okay
        if ! [ ${ERR} -eq 0 ]; then
          echo -e "${YELLOW}${BOLD}Warning: Could not download icon - check URL${RESET}"
          exit 1
        else
          echo "✅ Icon check succeeded"
        fi
      else
        echo -e "${YELLOW}${BOLD}Warning: Icon not found! Icon presence is mandatory!"
        exit 1
      fi
    fi
  done

  echo ""
done

# Clean up
rm -rf ${TMP}